### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by SemyonSinchenko** [danielbeach/datahobbit#5]
Hi! Thanks for the project!
Can you clarify please, under which terms the project can be used?

The perfect solution would be to add a LICENSE file with such a terms (like Apache 2.0, MIT, BSD, GPL, etc.)

**Comment by danielbeach** [comment]
@SemyonSinchenko what license would you recommend? I don't really have a preference.

**Comment by SemyonSinchenko** [comment]
@danielbeach For the python package I would say MIT. Most of dependencies of the project are MIT or Apache 2.0 (or both). Because ASF and MIT are compatible, I would recommend MIT.

**Comment by danielbeach** [comment]
I just added this project to crates.io https://crates.io/crates/datahobbit , I added `license = "MIT OR Apache-2.0"` to the cargo.toml file.

**Comment by SemyonSinchenko** [comment]
Thanks for the information!
